#!/usr/bin/env python3
"""
Generate FileView child measures for Scanner
Creates 9999 pre-defined child measures
"""

output_file = "Icycles/@Resources/ScannerChildren.inc"
num_children = 9999

with open(output_file, 'w', encoding='utf-16-le') as f:
    # Write BOM for UTF-16 LE
    f.write('\ufeff')

    # Header
    f.write("; ========================================\n")
    f.write("; FileView Children - Auto-generated\n")
    f.write("; DO NOT EDIT MANUALLY\n")
    f.write("; Generated by generate_children.py\n")
    f.write("; ========================================\n\n")

    # Generate 9999 children
    for i in range(1, num_children + 1):
        f.write(f"[MeasureFileViewChild{i}]\n")
        f.write("Measure=Plugin\n")
        f.write("Plugin=FileView\n")
        f.write("Path=[MeasureDesktopFileView]\n")
        f.write("Type=FileName\n")
        f.write(f"Index={i}\n")
        f.write("\n")

        # Progress indicator every 1000
        if i % 1000 == 0:
            print(f"Generated {i}/{num_children} children...")

print(f"✓ Generated {num_children} child measures in {output_file}")
