#!/usr/bin/env python3
"""
Generate FileView child measures for Scanner
Creates 9999 pre-defined child measures per Type
"""

import os

output_dir = "Icycles/@Resources"
num_children = 9999

# FileView Types to generate
types = [
    ("FileName", "File name"),
    ("FileSize", "File size in bytes"),
    ("FileDate", "File modification date"),
    ("FilePath", "Full file path"),
    ("FileType", "File extension/type")
]

# Ensure output directory exists
os.makedirs(output_dir, exist_ok=True)

for type_name, description in types:
    output_file = f"{output_dir}/ScannerBoilerplate-{type_name}.inc"

    print(f"Generating {type_name} children...")

    with open(output_file, 'w', encoding='utf-16-le') as f:
        # Write BOM for UTF-16 LE
        f.write('\ufeff')

        # Header
        f.write("; ========================================\n")
        f.write(f"; FileView Children - {description}\n")
        f.write("; DO NOT EDIT MANUALLY\n")
        f.write("; Generated by generate_children.py\n")
        f.write("; ========================================\n\n")

        # Generate 9999 children for this type
        for i in range(1, num_children + 1):
            f.write(f"[MeasureFileViewChild_{type_name}{i}]\n")
            f.write("Measure=Plugin\n")
            f.write("Plugin=FileView\n")
            f.write("Path=[MeasureDesktopFileView]\n")
            f.write(f"Type={type_name}\n")
            f.write(f"Index={i}\n")
            f.write("\n")

        print(f"  ✓ Generated {num_children} children in {output_file}")

print(f"\n✓ All boilerplate files generated in {output_dir}/")
print(f"  Total measures: {num_children * len(types)} ({num_children} × {len(types)} types)")

