-- ========================================
-- ICYCLES - Drawer Widget Generator
-- ========================================
-- Generates drawer .ini files from category data
-- Creates expandable hover widgets for Desktop
-- ========================================

function Initialize()
  -- Called on skin load
end

function Update()
  return ""
end

-- ========================================
-- MAIN FUNCTION: Generate all drawers
-- ========================================
function GenerateAllDrawers()
  -- Load categories
  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local masterPath = skinPath .. "Data\\Categories.ldb"
  local masterData = LoadDataFile(masterPath)

  if not masterData or not masterData.categories then
    LogError("No categories found to generate")
    return false
  end

  local generatedCount = 0

  -- Generate drawer for each category
  for _, categoryName in ipairs(masterData.categories) do
    local catPath = skinPath .. "CatData\\" .. categoryName .. ".ldb"
    local catData = LoadDataFile(catPath)

    if catData then
      local success = GenerateDrawer(categoryName, catData)
      if success then
        generatedCount = generatedCount + 1
      end
    else
      LogError("Failed to load category for generation: " .. categoryName)
    end
  end

  -- Update last generated timestamp
  masterData.lastGenerated = os.time()
  SaveMasterData(masterData)

  print("Generator: Generated " .. generatedCount .. " drawer widgets")
  return generatedCount > 0
end

-- ========================================
-- GENERATE DRAWER: Create single drawer .ini
-- ========================================
function GenerateDrawer(categoryName, categoryData)
  local metadata = categoryData.metadata
  local items = categoryData.items

  -- Calculate dimensions
  local itemCount = #items
  local itemHeight = 40
  local itemSpacing = 8
  local drawerPadding = 16
  local titleHeight = 80
  local iconSize = 48

  local drawerHeight = (itemCount * (itemHeight + itemSpacing)) + (drawerPadding * 2) + titleHeight
  local drawerWidth = 280

  -- Build .ini content
  local iniContent = BuildDrawerIni(categoryName, metadata, items, drawerWidth, drawerHeight, itemHeight, itemSpacing, iconSize)

  -- Write to file
  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local outputPath = skinPath .. "Drawers\\" .. categoryName .. ".ini"

  local success = WriteToFile(outputPath, iniContent)

  if success then
    print("Generator: Created drawer for " .. categoryName)
  else
    LogError("Failed to create drawer for " .. categoryName)
  end

  return success
end

-- ========================================
-- BUILD DRAWER INI: Construct .ini content
-- ========================================
function BuildDrawerIni(categoryName, metadata, items, width, height, itemHeight, spacing, iconSize)
  local ini = {}

  -- Header
  table.insert(ini, "; ========================================")
  table.insert(ini, "; ICYCLES - Drawer Widget: " .. categoryName)
  table.insert(ini, "; Auto-generated by Generator.lua")
  table.insert(ini, "; Generated: " .. os.date("%Y-%m-%d %H:%M:%S"))
  table.insert(ini, "; ========================================")
  table.insert(ini, "")

  -- Metadata
  table.insert(ini, "[Metadata]")
  table.insert(ini, "Name=" .. categoryName .. " Drawer")
  table.insert(ini, "Author=Icycles Generator")
  table.insert(ini, "Version=1.0.0")
  table.insert(ini, "")

  -- Rainmeter section
  table.insert(ini, "[Rainmeter]")
  table.insert(ini, "Update=1000")
  table.insert(ini, "AccurateText=1")
  table.insert(ini, "DynamicWindowSize=1")
  table.insert(ini, "")

  -- Variables
  table.insert(ini, "@Include=#@#Variables.inc")
  table.insert(ini, "")
  table.insert(ini, "[Variables]")
  table.insert(ini, "DrawerExpanded=0")
  table.insert(ini, "CollapsedWidth=" .. iconSize)
  table.insert(ini, "ExpandedWidth=" .. width)
  table.insert(ini, "CollapsedHeight=" .. iconSize)
  table.insert(ini, "ExpandedHeight=" .. height)
  table.insert(ini, "CategoryName=" .. categoryName)
  table.insert(ini, "CategoryDisplayName=" .. metadata.displayName)
  table.insert(ini, "")

  -- Background meter (collapsed state)
  table.insert(ini, "[MeterCollapsedBg]")
  table.insert(ini, "Meter=Shape")
  table.insert(ini, "X=0")
  table.insert(ini, "Y=0")
  table.insert(ini, "Shape=Rectangle 0,0,#CollapsedWidth#,#CollapsedHeight#,8 | Fill Color #BgColor# | StrokeWidth 0")
  table.insert(ini, "MouseOverAction=[!SetVariable DrawerExpanded 1][!ShowMeter MeterExpandedBg][!ShowMeterGroup Items][!HideMeter MeterCollapsedBg][!UpdateMeter *][!Redraw]")
  table.insert(ini, "DynamicVariables=1")
  table.insert(ini, "")

  -- Category icon (collapsed state)
  table.insert(ini, "[MeterCollapsedIcon]")
  table.insert(ini, "Meter=String")
  table.insert(ini, "X=(#CollapsedWidth# / 2)")
  table.insert(ini, "Y=(#CollapsedHeight# / 2)")
  table.insert(ini, "StringAlign=CenterCenter")
  table.insert(ini, "FontFace=#FontFamily#")
  table.insert(ini, "FontSize=12")
  table.insert(ini, "FontWeight=#FontBold#")
  table.insert(ini, "FontColor=#TextColor#")
  table.insert(ini, "Text=#CategoryDisplayName#")
  table.insert(ini, "AntiAlias=1")
  table.insert(ini, "DynamicVariables=1")
  table.insert(ini, "")

  -- Background meter (expanded state)
  table.insert(ini, "[MeterExpandedBg]")
  table.insert(ini, "Meter=Shape")
  table.insert(ini, "X=0")
  table.insert(ini, "Y=0")
  table.insert(ini, "Shape=Rectangle 0,0,#ExpandedWidth#,#ExpandedHeight#,8 | Fill Color #DrawerBgColor# | StrokeWidth 0")
  table.insert(ini, "Hidden=1")
  table.insert(ini, "MouseLeaveAction=[!SetVariable DrawerExpanded 0][!HideMeter MeterExpandedBg][!HideMeterGroup Items][!ShowMeter MeterCollapsedBg][!UpdateMeter *][!Redraw]")
  table.insert(ini, "DynamicVariables=1")
  table.insert(ini, "")

  -- Category header (expanded state)
  table.insert(ini, "[MeterCategoryHeader]")
  table.insert(ini, "Meter=String")
  table.insert(ini, "X=16")
  table.insert(ini, "Y=16")
  table.insert(ini, "W=(#ExpandedWidth# - 32)")
  table.insert(ini, "H=60")
  table.insert(ini, "StringAlign=LeftCenter")
  table.insert(ini, "FontFace=#FontFamily#")
  table.insert(ini, "FontSize=#DrawerHeaderSize#")
  table.insert(ini, "FontWeight=#FontExtraBold#")
  table.insert(ini, "FontColor=#TextColor#")
  table.insert(ini, "Text=#CategoryName#")
  table.insert(ini, "StringCase=Upper")
  table.insert(ini, "AntiAlias=1")
  table.insert(ini, "Hidden=1")
  table.insert(ini, "Group=Items")
  table.insert(ini, "DynamicVariables=1")
  table.insert(ini, "")

  -- Generate item meters
  local yPos = 80  -- Start after header
  for i, item in ipairs(items) do
    local displayName = item.customName or item.name
    local itemY = yPos + ((i - 1) * (itemHeight + spacing))

    -- Item background
    table.insert(ini, "[MeterItem" .. i .. "Bg]")
    table.insert(ini, "Meter=Shape")
    table.insert(ini, "X=16")
    table.insert(ini, "Y=" .. itemY)
    table.insert(ini, "Shape=Rectangle 0,0,(#ExpandedWidth# - 32)," .. itemHeight .. ",4 | Fill Color 0,0,0,0 | StrokeWidth 0")
    table.insert(ini, "MouseOverAction=[!SetOption MeterItem" .. i .. "Bg Shape \"Rectangle 0,0,(#ExpandedWidth# - 32)," .. itemHeight .. ",4 | Fill Color #HoverBg# | StrokeWidth 0\"][!UpdateMeter MeterItem" .. i .. "Bg][!Redraw]")
    table.insert(ini, "MouseLeaveAction=[!SetOption MeterItem" .. i .. "Bg Shape \"Rectangle 0,0,(#ExpandedWidth# - 32)," .. itemHeight .. ",4 | Fill Color 0,0,0,0 | StrokeWidth 0\"][!UpdateMeter MeterItem" .. i .. "Bg][!Redraw]")
    table.insert(ini, "LeftMouseUpAction=[\"" .. item.path .. "\"]")
    table.insert(ini, "Hidden=1")
    table.insert(ini, "Group=Items")
    table.insert(ini, "DynamicVariables=1")
    table.insert(ini, "")

    -- Item text
    table.insert(ini, "[MeterItem" .. i .. "Text]")
    table.insert(ini, "Meter=String")
    table.insert(ini, "X=24")
    table.insert(ini, "Y=" .. (itemY + (itemHeight / 2)))
    table.insert(ini, "W=(#ExpandedWidth# - 48)")
    table.insert(ini, "StringAlign=LeftCenter")
    table.insert(ini, "FontFace=#FontFamily#")
    table.insert(ini, "FontSize=#ItemSize#")
    table.insert(ini, "FontWeight=#FontMedium#")
    table.insert(ini, "FontColor=#TextColor#")
    table.insert(ini, "Text=" .. EscapeIniValue(displayName))
    table.insert(ini, "ClipString=1")
    table.insert(ini, "AntiAlias=1")
    table.insert(ini, "Hidden=1")
    table.insert(ini, "Group=Items")
    table.insert(ini, "DynamicVariables=1")
    table.insert(ini, "")
  end

  return table.concat(ini, "\n")
end

-- ========================================
-- SAVE MASTER DATA: Update Categories.ldb
-- ========================================
function SaveMasterData(masterData)
  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local masterPath = skinPath .. "Data\\Categories.ldb"

  local serialized = SerializeTable(masterData)
  return WriteToFile(masterPath, "return " .. serialized)
end

-- ========================================
-- DEPLOY DRAWERS: Activate all generated skins
-- ========================================
function DeployDrawers()
  -- Load categories
  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local masterPath = skinPath .. "Data\\Categories.ldb"
  local masterData = LoadDataFile(masterPath)

  if not masterData or not masterData.categories then
    LogError("No categories to deploy")
    return false
  end

  -- Activate each drawer skin
  for i, categoryName in ipairs(masterData.categories) do
    local configName = "Icycles\\Drawers\\" .. categoryName
    SKIN:Bang("!ActivateConfig", configName, categoryName .. ".ini")

    -- Position drawers (simple vertical stack for now)
    local xPos = 50
    local yPos = 100 + (i * 60)
    SKIN:Bang("!Move", xPos, yPos, configName)
  end

  print("Generator: Deployed " .. #masterData.categories .. " drawers")
  return true
end

-- ========================================
-- UTILITY FUNCTIONS
-- ========================================

function LoadDataFile(path)
  local success, result = pcall(dofile, path)
  if success then
    return result
  else
    LogError("Failed to load data file: " .. path)
    return nil
  end
end

function WriteToFile(path, content)
  local tempPath = path .. ".tmp"

  local success, err = pcall(function()
    local file = io.open(tempPath, "w")
    if not file then
      error("Cannot open file for writing: " .. tempPath)
    end
    file:write(content)
    file:close()
  end)

  if not success then
    LogError("Failed to write file: " .. path)
    return false
  end

  -- Atomic rename
  os.remove(path)
  os.rename(tempPath, path)

  return true
end

function SerializeTable(tbl, indent)
  indent = indent or 0
  local spacing = string.rep("  ", indent)
  local result = "{\n"

  for key, value in pairs(tbl) do
    local keyStr = type(key) == "string" and string.format("%s  %s = ", spacing, key) or string.format("%s  [%d] = ", spacing, key)

    if type(value) == "table" then
      result = result .. keyStr .. SerializeTable(value, indent + 1) .. ",\n"
    elseif type(value) == "string" then
      result = result .. keyStr .. string.format("%q", value) .. ",\n"
    elseif type(value) == "number" then
      result = result .. keyStr .. tostring(value) .. ",\n"
    elseif type(value) == "boolean" then
      result = result .. keyStr .. tostring(value) .. ",\n"
    else
      result = result .. keyStr .. "nil,\n"
    end
  end

  result = result .. spacing .. "}"
  return result
end

function EscapeIniValue(str)
  -- Escape special characters for INI values
  str = str:gsub("\"", "\"\"")  -- Double quotes
  str = str:gsub("\n", "")       -- Remove newlines
  str = str:gsub("\r", "")       -- Remove carriage returns
  return str
end

function LogError(message)
  local logPath = SKIN:GetVariable("CURRENTPATH") .. "Logs\\errors.log"
  local file = io.open(logPath, "a")
  if file then
    file:write(string.format("[%s] Generator: %s\n", os.date("%Y-%m-%d %H:%M:%S"), message))
    file:close()
  end
  print("ERROR: " .. message)
end
