-- ========================================
-- LAYOUT HELPER
-- ========================================
-- Provides font-independent positioning
-- Queries Rainmeter's actual text metrics
-- ========================================

function Initialize()
  -- Create hidden test meters to measure actual text rendering
  CreateTestMeters()
end

function CreateTestMeters()
  -- These will be generated dynamically to measure text
  print("LayoutHelper: Initialized")
end

-- ========================================
-- GET ACTUAL LINE HEIGHT
-- ========================================
function GetActualLineHeight(fontSize, fontFace)
  -- Get the measure that renders text at this size
  local measureName = "MeasureLineHeight" .. fontSize
  local measure = SKIN:GetMeasure(measureName)

  if not measure then
    print("LayoutHelper: WARNING - No measure found for fontSize=" .. fontSize)
    -- Fallback to estimated height
    return math.ceil(fontSize * 1.6)  -- Typical line height ratio
  end

  local height = measure:GetH()
  print("LayoutHelper: Actual line height for fontSize=" .. fontSize .. " is " .. height .. "px")

  return height
end

-- ========================================
-- CALCULATE CLICK INDEX (FONT-INDEPENDENT)
-- ========================================
function CalculateClickIndex(mouseY, listStartY, fontSize)
  local lineHeight = GetActualLineHeight(fontSize)
  local relativeY = mouseY - listStartY
  local index = math.floor(relativeY / lineHeight) + 1

  print("LayoutHelper: Click at Y=" .. mouseY .. ", listStartY=" .. listStartY ..
        ", lineHeight=" .. lineHeight .. " → index=" .. index)

  return index
end

-- ========================================
-- GENERATE LINE HEIGHT METERS
-- ========================================
function GenerateLineHeightMeters()
  -- Generate hidden meters for measuring text heights
  local content = [[
; Auto-generated by LayoutHelper.lua
; These meters measure actual text rendering heights

[MeasureLineHeight10]
Measure=String
Text=Ag
FontFace=#FontFamily#
FontSize=10
AntiAlias=1
Hidden=1

[MeasureLineHeight12]
Measure=String
Text=Ag
FontFace=#FontFamily#
FontSize=12
AntiAlias=1
Hidden=1

[MeasureLineHeight18]
Measure=String
Text=Ag
FontFace=#FontFamily#
FontSize=18
AntiAlias=1
Hidden=1
]]

  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local includePath = skinPath .. "@Resources\\LineHeightMeters.inc"

  local file = io.open(includePath, "w")
  if file then
    file:write(content)
    file:close()
    print("LayoutHelper: Generated LineHeightMeters.inc")
    return true
  else
    print("LayoutHelper: ERROR - Could not write LineHeightMeters.inc")
    return false
  end
end
