-- ========================================
-- ICYCLES - Quick Setup Helper
-- ========================================
-- Creates default categories for testing
-- Run this from Rainmeter: !CommandMeasure ScriptQuickSetup "CreateDefaultCategories()"
-- ========================================

function Initialize()
  -- Called on skin load
end

function Update()
  return ""
end

-- ========================================
-- CREATE DEFAULT CATEGORIES
-- ========================================
function CreateDefaultCategories()
  local categories = {
    "Development",
    "Creative",
    "Gaming",
    "Tools",
    "Office"
  }

  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local catDataPath = skinPath .. "CatData\\"

  print("QuickSetup: Creating default categories...")

  -- Create each category file
  for i, categoryName in ipairs(categories) do
    local categoryData = {
      metadata = {
        name = categoryName,
        displayName = GetDisplayName(categoryName),
        icon = nil,
        color = nil,
        order = i,
        created = os.time(),
        modified = os.time(),
        version = "1.0.0"
      },
      items = {}
    }

    local filePath = catDataPath .. categoryName .. ".ldb"
    local serialized = SerializeTable(categoryData)

    local success = WriteToFile(filePath, "return " .. serialized)
    if success then
      print("QuickSetup: Created " .. categoryName)
    else
      print("QuickSetup: FAILED to create " .. categoryName)
    end
  end

  -- Create master index
  local masterData = {
    categories = categories,
    order = {1, 2, 3, 4, 5},
    lastGenerated = os.time(),
    version = "1.0.0"
  }

  local masterPath = skinPath .. "Data\\Categories.ldb"
  local masterSerialized = SerializeTable(masterData)
  local masterSuccess = WriteToFile(masterPath, "return " .. masterSerialized)

  if masterSuccess then
    print("QuickSetup: [OK] All categories created successfully!")
    print("QuickSetup: Now click REBUILD LIST to scan Desktop")
    SKIN:Bang("!UpdateMeasure", "ScriptConfigurator")
    SKIN:Bang("!CommandMeasure", "ScriptConfigurator", "LoadAllCategories()")
    SKIN:Bang("!UpdateMeter", "*")
    SKIN:Bang("!Redraw")
  else
    print("QuickSetup: ERROR - Failed to create master index")
  end

  return true
end

function GetDisplayName(categoryName)
  local displayNames = {
    Development = "DEV",
    Creative = "ART",
    Gaming = "GAME",
    Tools = "TOOL",
    Office = "WORK"
  }
  return displayNames[categoryName] or categoryName:sub(1, 4):upper()
end

function WriteToFile(path, content)
  local tempPath = path .. ".tmp"

  local success, err = pcall(function()
    local file = io.open(tempPath, "w")
    if not file then
      error("Cannot open file for writing: " .. tempPath)
    end
    file:write("-- Auto-generated by QuickSetup.lua\n")
    file:write("-- Created: " .. os.date("%Y-%m-%d %H:%M:%S") .. "\n\n")
    file:write(content)
    file:close()
  end)

  if not success then
    print("ERROR: Failed to write file: " .. path)
    return false
  end

  os.remove(path)
  os.rename(tempPath, path)

  return true
end

function SerializeTable(tbl, indent)
  indent = indent or 0
  local spacing = string.rep("  ", indent)
  local result = "{\n"

  for key, value in pairs(tbl) do
    local keyStr = type(key) == "string" and string.format("%s  %s = ", spacing, key) or string.format("%s  [%d] = ", spacing, key)

    if type(value) == "table" then
      result = result .. keyStr .. SerializeTable(value, indent + 1) .. ",\n"
    elseif type(value) == "string" then
      result = result .. keyStr .. string.format("%q", value) .. ",\n"
    elseif type(value) == "number" then
      result = result .. keyStr .. tostring(value) .. ",\n"
    elseif type(value) == "boolean" then
      result = result .. keyStr .. tostring(value) .. ",\n"
    else
      result = result .. keyStr .. "nil,\n"
    end
  end

  result = result .. spacing .. "}"
  return result
end
