-- ========================================
-- ICYCLES - User Desktop Info Gatherer
-- ========================================
-- Collects environment data on startup
-- Saves to Data/UserDesktopData.ldb
-- ========================================

function Initialize()
  -- Will be called when skin loads
end

function Update()
  -- Runs on every update cycle
  return ""
end

-- ========================================
-- MAIN FUNCTION: Gather Environment Data
-- ========================================
function GatherDesktopInfo()
  local data = {}

  -- Get Rainmeter paths
  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local rootPath = SKIN:GetVariable("ROOTCONFIGPATH")

  -- Get screen dimensions
  data.screenWidth = tonumber(SKIN:GetVariable("SCREENAREAX")) + tonumber(SKIN:GetVariable("SCREENAREAWIDTH")) or 1920
  data.screenHeight = tonumber(SKIN:GetVariable("SCREENAREAY")) + tonumber(SKIN:GetVariable("SCREENAREAHEIGHT")) or 1080
  data.workAreaWidth = tonumber(SKIN:GetVariable("SCREENAREAWIDTH")) or 1920
  data.workAreaHeight = tonumber(SKIN:GetVariable("SCREENAREAHEIGHT")) or 1080

  -- Get DPI (Rainmeter provides this)
  data.dpi = tonumber(SKIN:GetVariable("SCREENDPI")) or 96

  -- Get Desktop path using environment variable
  -- Rainmeter has access to USERPROFILE env var
  local userProfile = os.getenv("USERPROFILE") or "C:\\Users\\Default"
  data.desktopPath = userProfile .. "\\Desktop"

  -- Get Rainmeter version
  data.rainmeterVersion = SKIN:GetVariable("RAINMETERVERSION") or "Unknown"

  -- Store paths
  data.skinPath = skinPath
  data.rootPath = rootPath

  -- Timestamp
  data.lastScan = os.time()

  -- Initial desktop item count (will be updated by Scanner)
  data.desktopItemCount = 0

  -- Schema version
  data.version = "1.0.0"

  return data
end

-- ========================================
-- SAVE FUNCTION: Write data to file
-- ========================================
function SaveDesktopInfo()
  local success, data = pcall(GatherDesktopInfo)

  if not success then
    LogError("Failed to gather desktop info: " .. tostring(data))
    return false
  end

  -- Serialize data to Lua table format
  local serialized = SerializeTable(data)

  -- Build file path
  local skinPath = SKIN:GetVariable("CURRENTPATH")
  local filePath = skinPath .. "Data\\UserDesktopData.ldb"

  -- Write to temp file first (atomic write)
  local tempPath = filePath .. ".tmp"
  local success, err = pcall(function()
    local file = io.open(tempPath, "w")
    if not file then
      error("Cannot open file for writing: " .. tempPath)
    end
    file:write("-- Auto-generated by UserDesktopInfo.lua\n")
    file:write("-- Last updated: " .. os.date("%Y-%m-%d %H:%M:%S") .. "\n\n")
    file:write("return " .. serialized)
    file:close()
  end)

  if not success then
    LogError("Failed to write UserDesktopData.ldb: " .. tostring(err))
    return false
  end

  -- Rename temp to actual (atomic operation)
  os.remove(filePath)  -- Remove old file first
  local renameSuccess = os.rename(tempPath, filePath)

  if not renameSuccess then
    LogError("Failed to rename temp file to UserDesktopData.ldb")
    return false
  end

  print("UserDesktopInfo: Saved successfully")
  return true
end

-- ========================================
-- UTILITY: Serialize Lua table to string
-- ========================================
function SerializeTable(tbl, indent)
  indent = indent or 0
  local spacing = string.rep("  ", indent)
  local result = "{\n"

  for key, value in pairs(tbl) do
    local keyStr = type(key) == "string" and string.format("%s  %s = ", spacing, key) or string.format("%s  [%s] = ", spacing, tostring(key))

    if type(value) == "table" then
      result = result .. keyStr .. SerializeTable(value, indent + 1) .. ",\n"
    elseif type(value) == "string" then
      result = result .. keyStr .. string.format("%q", value) .. ",\n"
    elseif type(value) == "number" then
      result = result .. keyStr .. tostring(value) .. ",\n"
    elseif type(value) == "boolean" then
      result = result .. keyStr .. tostring(value) .. ",\n"
    else
      result = result .. keyStr .. "nil,\n"
    end
  end

  result = result .. spacing .. "}"
  return result
end

-- ========================================
-- UTILITY: Error logging
-- ========================================
function LogError(message)
  local logPath = SKIN:GetVariable("CURRENTPATH") .. "Logs\\errors.log"
  local file = io.open(logPath, "a")
  if file then
    file:write(string.format("[%s] UserDesktopInfo: %s\n", os.date("%Y-%m-%d %H:%M:%S"), message))
    file:close()
  end
  print("ERROR: " .. message)
end
